image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7

##
## Various steps to be followed by the build
##
stages:
  - build
  - hnstep
  - wstep
  - flsstep
  - rstep
  - draw
  - imagebuild
  - cleanup

## Checkout the submodule
variables:
  GIT_SUBMODULE_STRATEGY: normal
  BUILD_IMAGE: atlas/analysisbase:21.2.91
##
## Common setup for all jobs
##
before_script:
  - set +e
  - source setup.sh #sources the setup in the TRExFitter package (consistent with user's setup)
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}${LD_LIBRARY_PATH:+:}$PWD/build/lib

##
## "build" step: first compiles the code
##    Artifact: keeps the log file of the compilation
##
compile:
  stage: build
  script:
     - mkdir -p build && cd build
     - cmake .. | tee cmake.log
     - make clean #make sure we don't have residual compilation results
     - make -j4 2>&1 | tee -a cmake.log  #dump the log files
  artifacts:
     paths:
      - build

##
## "hnstep" step: produces the input histograms for TRExFitter
##    Artifact: keeps the FitExample folder
##
histograms_full:
    stage: hnstep
    needs:
      - compile
    script:
      - trex-fitter h test/configs/FitExample.config
      - ls
      - ls FitExample/Histograms/
    artifacts:
      paths:
        - FitExample

histograms_statonly:
    stage: hnstep
    needs:
      - compile
    script:
      - trex-fitter h test/configs/FitExampleStatOnly.config StatOnlyFit=TRUE
      - ls
      - ls FitExampleStatOnly/Histograms/
    artifacts:
      paths:
        - FitExampleStatOnly

histograms_morph:
    stage: hnstep
    needs:
      - compile
    script:
      - trex-fitter h test/configs/FitExampleMorphing.config
      - ls
      - ls FitExampleMorphing/Histograms/
    artifacts:
      paths:
        - FitExampleMorphing

histograms_ntuple:
    stage: hnstep
    needs:
      - compile
    script:
      - trex-fitter n test/configs/FitExampleNtuple.config
      - ls
      - ls FitExampleNtuple/Histograms/
    artifacts:
      paths:
        - FitExampleNtuple

##
## "wstep" step: produces the workspace
##    Artifact: keeps the FitExample folder
##
workspace_full:
    stage: wstep
    needs:
      - compile
      - histograms_full
    script:
      - trex-fitter w test/configs/FitExample.config >& LOG_w
      - cat LOG_w | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_w
      - ls
      - set -e
      - ls FitExample
      - ls FitExample/RooStats/
      - source test/scripts/FitExample/check_step_w.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExample

workspace_statonly:
    stage: wstep
    needs:
      - compile
      - histograms_statonly
    script:
      - trex-fitter w test/configs/FitExampleStatOnly.config StatOnlyFit=TRUE >& LOG_STATONLY_w
      - cat LOG_STATONLY_w | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_STATONLY_w
      - ls
      - set -e
      - ls FitExampleStatOnly
      - ls FitExampleStatOnly/RooStats/
      - source test/scripts/FitExampleStatOnly/check_step_w_statonly.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExampleStatOnly

workspace_morph:
    stage: wstep
    needs:
      - compile
      - histograms_morph
    script:
      - trex-fitter w test/configs/FitExampleMorphing.config >& LOG_MORPH_w
      - cat LOG_MORPH_w | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_MORPH_w
      - ls
      - set -e
      - ls FitExampleMorphing
      - ls FitExampleMorphing/RooStats/
      - source test/scripts/FitExampleMorphing/check_step_w_morph.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExampleMorphing

workspace_ntuple:
    stage: wstep
    needs:
      - compile
      - histograms_ntuple
    script:
      - trex-fitter w test/configs/FitExampleNtuple.config >& LOG_NTUPLE_w
      - cat LOG_NTUPLE_w | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_NTUPLE_w
      - ls
      - set -e
      - ls FitExampleNtuple
      - ls FitExampleNtuple/RooStats/
      - source test/scripts/FitExampleNtuple/check_step_w_ntuple.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExampleNtuple

##
## "flsstep" step: performs the fit
##    Artifact: keeps the FitExample folder
##
fit_full:
    stage: flsstep
    needs:
      - compile
      - histograms_full
      - workspace_full
    script:
      - trex-fitter f test/configs/FitExample.config >& LOG_f
      - cat LOG_f | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_f
      - ls
      - set -e
      - ls FitExample
      - ls FitExample/Fits/
      - cat FitExample/Fits/*.txt
      - source test/scripts/FitExample/check_step_f.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExample

fit_statonly:
    stage: flsstep
    needs:
      - compile
      - histograms_statonly
      - workspace_statonly
    script:
      - trex-fitter f test/configs/FitExampleStatOnly.config StatOnlyFit=TRUE >& LOG_STATONLY_f
      - cat LOG_STATONLY_f | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_STATONLY_f
      - ls
      - set -e
      - ls FitExampleStatOnly
      - ls FitExampleStatOnly/Fits/
      - cat FitExampleStatOnly/Fits/*.txt
      - source test/scripts/FitExampleStatOnly/check_step_f_statonly.sh
      - echo "=> Passed quick logfile checks"

fit_morph:
    stage: flsstep
    needs:
      - compile
      - histograms_morph
      - workspace_morph
    script:
      - trex-fitter f test/configs/FitExampleMorphing.config >& LOG_MORPH_f
      - cat LOG_MORPH_f | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_MORPH_f
      - ls
      - set -e
      - ls FitExampleMorphing
      - ls FitExampleMorphing/Fits/
      - cat FitExampleMorphing/Fits/*.txt
      - source test/scripts/FitExampleMorphing/check_step_f_morph.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExampleMorphing

fit_ntuple:
    stage: flsstep
    needs:
      - compile
      - histograms_ntuple
      - workspace_ntuple
    script:
      - trex-fitter f test/configs/FitExampleNtuple.config >& LOG_NTUPLE_f
      - cat LOG_NTUPLE_f | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_NTUPLE_f
      - ls
      - set -e
      - ls FitExampleNtuple
      - ls FitExampleNtuple/Fits/
      - cat FitExampleNtuple/Fits/*.txt
      - source test/scripts/FitExampleNtuple/check_step_f_ntuple.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExampleNtuple

##
## "flsstep" step: compute the limits
##    Artifact: keeps the FitExample folder
##
limit:
    stage: flsstep
    needs:
      - compile
      - histograms_full
      - workspace_full
    script:
      - trex-fitter l test/configs/FitExample.config >& LOG_l
      - cat LOG_l | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_l
      - ls
      - set -e
      - ls FitExample
      - ls FitExample/Limits/
      - source test/scripts/FitExample/check_step_l.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExample

##
## "flsstep" step: compute the significance
##    Artifact: keeps the FitExample folder
##
significance:
    stage: flsstep
    needs:
      - compile
      - histograms_full
      - workspace_full
    script:
      - trex-fitter s test/configs/FitExample.config >& LOG_s
      - cat LOG_s | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_s
      - ls
      - set -e
      - ls FitExample
      - ls FitExample/Significance/
      - source test/scripts/FitExample/check_step_s.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExample

##
## "rstep" step: compute the ranking
##    Artifact: keeps the FitExample folder
##
ranking:
    stage: rstep
    needs:
      - compile
      - histograms_full
      - workspace_full
      - fit_full
    script:
      - trex-fitter r test/configs/FitExample.config >& LOG_r
      - cat LOG_r | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_r
      - ls
      - set -e
      - source test/scripts/FitExample/check_step_r.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExample

##
## "draw" step: performs the prefit plots
##    Artifact: keeps the Plots folder
##
draw_prefit:
    stage: draw
    needs:
      - compile
      - histograms_full
    script:
      - trex-fitter d test/configs/FitExample.config >& LOG_d
      - cat LOG_d | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_d
      - ls
      - set -e
      - ls FitExample
      - ls FitExample/Plots/
      - source test/scripts/FitExample/check_step_d.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExample/Plots/

draw_prefit_morph:
    stage: draw
    needs:
      - compile
      - histograms_morph
    script:
      - trex-fitter d test/configs/FitExampleMorphing.config >& LOG_MORPH_d
      - cat LOG_MORPH_d | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_MORPH_d
      - ls
      - set -e
      - ls FitExampleMorphing
      - ls FitExampleMorphing/Plots/
      - source test/scripts/FitExampleMorphing/check_step_d_morph.sh
      - echo "=> Passed quick logfile checks"

draw_prefit_ntuple:
    stage: draw
    needs:
      - compile
      - histograms_ntuple
    script:
      - trex-fitter d test/configs/FitExampleNtuple.config >& LOG_NTUPLE_d
      - cat LOG_NTUPLE_d | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_NTUPLE_d
      - ls
      - set -e
      - ls FitExampleNtuple
      - ls FitExampleNtuple/Plots/
      - source test/scripts/FitExampleNtuple/check_step_d_ntuple.sh
      - echo "=> Passed quick logfile checks"

##
## "draw" step: performs the postfit plots
##    Artifact: keeps the Plots folder
##
draw_postfit:
    stage: draw
    needs:
      - compile
      - histograms_full
      - fit_full
    script:
      - trex-fitter p test/configs/FitExample.config >& LOG_p
      - cat LOG_p | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_p
      - ls
      - set -e
      - ls FitExample
      - ls FitExample/Plots/
      - source test/scripts/FitExample/check_step_p.sh
      - echo "=> Passed quick logfile checks"
    artifacts:
      paths:
        - FitExample/Plots/

draw_postfit_morph:
    stage: draw
    needs:
      - compile
      - histograms_morph
      - fit_morph
    script:
      - trex-fitter p test/configs/FitExampleMorphing.config >& LOG_MORPH_p
      - cat LOG_MORPH_p | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_MORPH_p
      - ls
      - set -e
      - ls FitExampleMorphing
      - ls FitExampleMorphing/Plots/
      - source test/scripts/FitExampleMorphing/check_step_p_morph.sh
      - echo "=> Passed quick logfile checks"

draw_postfit_ntuple:
    stage: draw
    needs:
      - compile
      - histograms_ntuple
      - fit_ntuple
    script:
      - trex-fitter p test/configs/FitExampleNtuple.config >& LOG_NTUPLE_p
      - cat LOG_NTUPLE_p | grep -v "TRExFitter" >& temp_log && mv temp_log LOG_NTUPLE_p
      - ls
      - set -e
      - ls FitExampleNtuple
      - ls FitExampleNtuple/Plots/
      - source test/scripts/FitExampleNtuple/check_step_p_ntuple.sh
      - echo "=> Passed quick logfile checks"

##
## image creation step: creates Docker container for master branch
##    tagging image as "latest"
##
build_img_latest:
  needs:
    - compile
  stage: imagebuild
  image: gitlab-registry.cern.ch/ci-tools/docker-image-builder:no_kaniko
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    FROM: $BUILD_IMAGE
    TO: $CI_REGISTRY_IMAGE:latest
  tags:
    - docker-image-build
  script:
    - ignore
  only:
    - master

##
## image creation step: creates Docker container for repository tags
##    CI_COMMIT_REF_SLUG: either branch name or tag name
##
build_img_tag:
  needs:
    - compile
  stage: imagebuild
  image: gitlab-registry.cern.ch/ci-tools/docker-image-builder:no_kaniko
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    FROM: $BUILD_IMAGE
    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - docker-image-build
  script:
    - ignore
  only:
    - tags
