image: docker.cern.ch/linuxsupport/cc7-base:latest

stages:
    - prepare
    - hstep
    - wstep
    - flsstep
    - cleanup

before_script:
   - yum -y groupinstall "Development Tools"
   - yum -y install libSM libX11 libXext libXpm libXft man
   - set +e
   - source setup.sh
   - which root
   - which make
   - root -l -b -q
   - ls
   - ls ExampleInputs

compile:
    stage: prepare
    tags:
      - cvmfs
    script:
      - make clean
      - make > make.log 2>&1
    artifacts:
      paths:
        - make.log
        - myFit.exe

input_prod:
    stage: prepare
    tags:
      - cvmfs
    script:
      - root -l -b -q CreateHistograms.C
    artifacts:
      paths:
        - ExampleInputs

hstep:
    stage: hstep
    tags:
      - cvmfs
    script:
      - ./myFit.exe h config/myFit.config
      - ls
      - ls FitExample/Histograms/
    artifacts:
      paths:
        - FitExample

wstep:
    stage: wstep
    tags:
      - cvmfs
    script:
      - ./myFit.exe w config/myFit.config
      - ls
      - ls FitExample
      - ls FitExample/RooStats/
    artifacts:
      paths:
        - FitExample

fstep:
    stage: flsstep
    tags:
      - cvmfs
    script:
      - ./myFit.exe f config/myFit.config
      - ls
      - ls FitExample
      - ls FitExample/Fits/
      - cat FitExample/Fits/
    artifacts:
      paths:
        - FitExample

lstep:
    stage: flsstep
    tags:
      - cvmfs
    script:
      - ./myFit.exe l config/myFit.config
      - ls
      - ls FitExample
      - ls FitExample/Limits/
    artifacts:
      paths:
        - FitExample

sstep:
    stage: flsstep
    tags:
      - cvmfs
    script:
      - ./myFit.exe s config/myFit.config
      - ls
      - ls FitExample
      - ls FitExample/Significance/
    artifacts:
      paths:
        - FitExample
