image: mazurov/cern-root

# stages is used to defined build stages that can be used by jobs. The ordering
# of elements in stages defines the ordering of builds' execution:
#       - builds of the same stage are run in parallel
#       - builds of the next stage are run after success
stages:
    - build
    - test
    - cleanup

before_script:
  - yum -y install make
  - ls
  - which make
  - which root


root_setup:
    stage: build
    script:
      - root -l -b -q

build_job:
    stage: build
    script:
      - make > make.log 2>&1
      - make clean
    artifacts:
      paths:
        - make.log
