site_name: TRExFitter documentation
site_description: Documentation for TRExFitter
site_author: TRExFitter team
site_url: https://trexfitter-docs.web.cern.ch/

repo_name: GitLab
repo_url: https://gitlab.cern.ch/TRExStats/TRExFitter
edit_uri: 'tree/master/docs'

theme:
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo:
        icon: 'insert_chart'
    favicon: 'img/favicon.png'

nav:
    - Introduction: index.md
    - Setup: setup.md
    - 'Short walkthrough': short_walkthrough.md
    - 'Common fit problems':
      - 'Fit problems': fit_problems/introduction.md
      - 'Technical aspects': fit_problems/technical_aspects.md
      - 'Preparation': fit_problems/preparation.md
      - 'Problems and solutions': fit_problems/problems.md
      - 'Cross-checks of results': fit_problems/checks.md
      - 'FAQ': fit_problems/faq.md
    - 'FAQ': faq.md
    - 'Settings': settings.md
    - 'Basicd Tutorial (2020)':
        - 'Introduction': BasicTutorial2020/Introduction.md
        - 'Explanations of some key features':
            - 'Limit explanation': BasicTutorial2020/Limit.md
            - 'Significance explanation': BasicTutorial2020/Significance.md
            - 'Ranking explanation': BasicTutorial2020/Ranking.md
            - 'Grouped Impact explanation': BasicTutorial2020/GroupedImpact.md
        - 'Newly added features':
            - 'Goodness-of-fit': BasicTutorial2020/GOF.md
            - 'Building envelopes': BasicTutorial2020/Envelope.md
            - 'Force shape by hand': BasicTutorial2020/Shape.md
    - 'Advanced Tutorial (2020)':
        - 'Introduction': AdvancedTutorial2020/Introduction.md
        - 'Profile-likelihood with multiple templates': AdvancedTutorial2020/Morphing.md
        - 'Using Expression': AdvancedTutorial2020/Expression.md
        - 'Profile-likelihood unfolding': AdvancedTutorial2020/Unfolding.md
        - 'Mixed data and MC fits': AdvancedTutorial2020/Mixed.md

markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.arithmatex
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.smartsymbols
    - pymdownx.superfences

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
